// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynnqilrwqiqvcpddeorb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlubnFpbHJ3cWlxdmNwZGRlb3JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MTQ3MzgsImV4cCI6MjA2ODM5MDczOH0.i3b54p5XTzfXBBw5JvA_mv_Q5hSozQaCRLP-aSVkNgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});